from typing import List, Optional
from pydantic import BaseModel, Field


class EssayRequest(BaseModel):
    task: str = Field(..., description="The essay topic or writing prompt to be executed by the agent")
    max_revisions: int = Field(default=2, ge=1, le=10, description="Maximum revision cycles")


class EssayResponse(BaseModel):
    task: str
    plan: Optional[str] = Field(default=None, description="Essay plan outline generated by planner")
    draft: Optional[str] = Field(default=None, description="Final essay draft")
    critique: Optional[str] = Field(default=None, description="Critique/reflection on the draft")
    content: Optional[List[str]] = Field(default_factory=list, description="Gathered research content")
    revision_number: Optional[int] = Field(default=1, description="Number of revisions completed")
